# .github/dependabot.yml
version: 2
registries:
  nav_github_packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    scope: "@navikt"
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - nav_github_packages
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
      semver-major-days: 30
    open-pull-requests-limit: 15
    labels:
      - "dependencies"
    commit-message:
      prefix: "dependabot-bump"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
